### ISSUE TITLE
No answer with Version 0.5.20

### ISSUE THREAD

**Issue by pbksol** [Supereg/homebridge-http-switch#32]
After updating to Version 0.5.20 all devices are shown as offline (not answering).

The Log shows "[Steckdose 0] getStatus() http request returned http error code: 200".

Without digging deeper… The Status-URL is somewhat broken. Because the MQTT-Stuff is received properly an written to the Log "[Steckdose 0] MQTT updating characteristic On to false".

Every device has a statusPattern set.

**Comment by Supereg** [comment]
I see, I completely messed things up on my side. Thanks for the quick response.
v0.5.21 live now

**Comment by pbksol** [comment]
Sorry to say… But this one is worse… 0.5.21 is crashing Homebridge…

`    at Characteristic.On.emit (events.js:204:7)
    at emitMany (events.js:127:13)
    at HTTP_SWITCH.setStatus (/usr/local/lib/node_modules/homebridge-http-switch/index.js:395:22)
    at HTTP_SWITCH._makeSetRequest (/usr/local/lib/node_modules/homebridge-http-switch/index.js:434:14)
    at Object.multipleHttpRequests (/usr/local/lib/node_modules/homebridge-http-switch/node_modules/homebridge-http-base/http.js:124:44)
    at Object.reflectAll (/usr/local/lib/node_modules/homebridge-http-switch/node_modules/async/dist/async.js:4374:19)
    at arrayMap (/usr/local/lib/node_modules/homebridge-http-switch/node_modules/async/dist/async.js:1687:21)
    at reflect (/usr/local/lib/node_modules/homebridge-http-switch/node_modules/async/dist/async.js:4284:15)
    at wrapAsync (/usr/local/lib/node_modules/homebridge-http-switch/node_modules/async/dist/async.js:232:12)
    at isAsync (/usr/local/lib/node_modules/homebridge-http-switch/node_modules/async/dist/async.js:228:32)
TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined`

**Comment by Supereg** [comment]
Okay I see, I'm getting my head behind this, in the mean time you could downgrade to 0.5.19 in order for things to work properly again:
`sudo npm install -g homebridge-http-switch@0.5.19`

**Comment by Supereg** [comment]
okay, so v0.5.22 is live, testing on my side is successful. Would be great if you could run the plugin with your configuration if you got some time

**Comment by Tangheta** [comment]
0.5.22 works again with my old config. Thx!

**Comment by pbksol** [comment]
Version 0.5.22 works. Great :-)

**Comment by Supereg** [comment]
Sorry for the inconvenience

**Comment by Tangheta** [comment]
No inconvenience at all. Very happy with the new repeat feature. Just tested it. Works great. Thanks!

**Comment by Supereg** [comment]
Yes but I should definitely step up my testing game 😅 This shouldn't have slipped through 🙈
